{
 "title": "Predictor Regression Performance Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataset_name", "query": { "query": "label_values(dataset_name)" } },
   {
    "name": "feature",
    "query": {
     "query": "label_values(predictor:regression_performance:feature_error_bias, feature)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ME",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "predictor:regression_performance:quality{dataset=\"current\", metric=\"mean_error\", dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "ME"
    }
   ]
  },
  {
   "title": "MAE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "predictor:regression_performance:quality{dataset=\"current\", metric=\"mean_abs_error\", dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "ME"
    }
   ]
  },
  {
   "title": "MAPE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "predictor:regression_performance:quality{dataset=\"current\", metric=\"mean_abs_perc_error\", dataset_name=\"${dataset_name:raw}\"}"
    }
   ]
  },
  {
   "title": "Aggregated Metrics in time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "predictor:regression_performance:quality{dataset=\"current\", metric=\"mean_error\", dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "ME"
    },
    {
     "expr": "predictor:regression_performance:quality{dataset=\"current\", metric=\"mean_abs_error\", dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "MAE"
    },
    {
     "expr": "predictor:regression_performance:quality{dataset=\"current\", metric=\"mean_abs_perc_error\", dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "MAPE"
    }
   ]
  },
  { "title": "Feature error bias", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Error Bias: $feature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "repeat": "feature",
   "targets": [
    {
     "expr": "predictor:regression_performance:feature_error_bias{feature=\"${feature:raw}\", metric=\"current_over\", dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "Overestimation"
    },
    {
     "expr": "predictor:regression_performance:feature_error_bias{feature=\"${feature:raw}\", metric=\"current_under\", dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "Underestimation"
    },
    {
     "expr": "predictor:regression_performance:feature_error_bias{feature=\"${feature:raw}\", metric=\"current_majority\", dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "Majority"
    }
   ]
  }
 ]
}